name: bark
description: Flutter Client for Bark Authentication
version: 1.1.0
homepage: https://github.com/barksh

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  basic_utils: ^5.6.0
  dio: ^5.2.1+1
  flutter_web_auth_2: ^2.0.0
  logo: ^1.2.1
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: sh.bark.bark
        pluginClass: BarkPlugin
      ios:
        pluginClass: BarkPlugin
      linux:
        pluginClass: BarkPlugin
      macos:
        pluginClass: BarkPlugin
      windows:
        pluginClass: BarkPluginCApi
