name: bark_authentication
description: Flutter Client for Bark Authentication
version: 1.0.1
homepage: https://github.com/barksh

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  basic_utils: ^5.6.0
  dio: ^5.2.1+1
  flutter_web_auth_2: ^2.0.0
  logo: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: sh.bark.bark_authentication
        pluginClass: BarkAuthenticationPlugin
      ios:
        pluginClass: BarkAuthenticationPlugin
      linux:
        pluginClass: BarkAuthenticationPlugin
      macos:
        pluginClass: BarkAuthenticationPlugin
      windows:
        pluginClass: BarkAuthenticationPluginCApi
