name: bark_authentication
description: Flutter Client for Bark Authentication
version: 0.0.1
homepage: https://bark.sh

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_auth_2: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: sh.bark.bark_authentication
        pluginClass: BarkAuthenticationPlugin
      ios:
        pluginClass: BarkAuthenticationPlugin
      linux:
        pluginClass: BarkAuthenticationPlugin
      macos:
        pluginClass: BarkAuthenticationPlugin
      windows:
        pluginClass: BarkAuthenticationPluginCApi
